version: "3.9"
services:
  api:
    build: ./backend
    image: qa-break-room-api
    container_name: qa-break-room-api
    ports: ["4000:4000"]
    env_file: ./backend/.env
    restart: unless-stopped
