import { Router } from "express";
import { signup, login, forgotPassword, resetPassword, sendVerifyEmail, verifyEmail } from "../controllers/authController.js";
const r = Router();
r.post("/signup", signup);
r.post("/login",  login);
r.post("/forgot", forgotPassword);
r.post("/reset", resetPassword);
r.post("/send-verify", sendVerifyEmail);
r.post("/verify", verifyEmail);
export default r;
